language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - # Test Papermill from master (fixes pipes on Python 2.7)
  - pip install --upgrade https://github.com/nteract/papermill/archive/master.tar.gz
script:
  - # Test the (Python) notebook in the current Python environment
  - jupytext world_facts.md --set-kernel - --execute
  - # Test the (Bash) README
  - python -m bash_kernel.install
  - jupytext README.md --execute
