language: python
python:
#  - "2.7" # Restore this when https://github.com/nteract/papermill/issues/420 is fixed
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - # Test the (Python) notebook in the current Python environment
  - jupytext world_facts.md --set-kernel - --execute
  - # Test the (Bash) README
  - python -m bash_kernel.install
  - jupytext README.md --execute
