language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - # Test the (Python) notebook in the current Python environment
  - jupytext world_facts.md --set-kernel - --execute
  - # Test the (Bash) README
  - python -m bash_kernel.install
  - jupytext README.md --execute
